#server.port=8082
#spring.application.name=PROXY-SERVICE
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=rameshkrishnaprasath@gmail.com
#spring.mail.password=wtpgiuousoxbryzz
#spring.mail.properties.mail.smtp.auth=true
#
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

server:
  port: 8082
spring:
  application:
    name: PROXY-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: rameshkrishnaprasath@gmail.com
    password: wtpgiuousoxbryzz
    properties:
     mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
proxy: Proxy



